apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: quarkus-pipeline
  namespace: atos-development
spec:
  params:
    - name: REPO_URL
      type: string
    - name: REPO_NAME
      type: string
    - name: GIT_REVISION
      type: string
  tasks:
    - name: git-clone
      taskRef:
        kind: Task
        name: git-clone
      params:
        - name: url
          value: $(params.REPO_URL)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: sslVerify
          value: 'false'
        - name: noProxy
          value: 'true'
      workspaces:
        - name: output
          workspace: app-source
    - name: run-test-cases
      params:
        - name: GOALS
          value:
            - clean
            - test
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: maven
      workspaces:
        - name: source
          workspace: app-source
        - name: maven-settings
          workspace: maven-settings
    - name: application-build
      taskRef:
        kind: ClusterTask
        name: maven
      params:
        - name: GOALS
          value:
            - '-DskipTests'
            - package
      runAfter:
        - run-test-cases
      workspaces:
        - name: source
          workspace: app-source
        - name: maven-settings
          workspace: maven-settings
    - name: docker-build-and-push
      taskRef:
        kind: Task
        name: buildah
      params:
        - name: IMAGE
          value: "quay.io/tailorshift/$(params.REPO_NAME):main"
        - name: DOCKERFILE
          value: 'src/main/docker/Dockerfile.jvm'
        - name: SKIP_PUSH
          value: 'true'
      runAfter:
        - application-build
      workspaces:
        - name: source
          workspace: app-source
  workspaces:
    - name: app-source
    - name: maven-settings